# Generated by Django 5.2.9 on 2025-12-15 14:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_supervisor_alter_attendancerecord_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_no', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('rejoining_date', models.DateField(blank=True, null=True)),
                ('month', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('attendance_data', models.JSONField()),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-uploaded_at', 'ref_no'],
                'unique_together': {('ref_no', 'month', 'year')},
            },
        ),
    ]
