# Generated by Django 5.2.9 on 2025-12-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_employeeattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='duty_stop',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='new_joining',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='re_joining',
            field=models.DateField(blank=True, null=True),
        ),
    ]
