# Generated by Django 5.2.9 on 2025-12-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobvacancy',
            name='filled_positions',
            field=models.IntegerField(default=0, help_text='Number of positions filled'),
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='total_positions',
            field=models.IntegerField(default=1, help_text='Total number of positions available'),
        ),
    ]
